server:
  port: 9998

spring:
  datasource:
    username: root
    password: 315400sxl
    url: jdbc:mysql:///ruiji
  redis:
    port: 6379
    host: localhost
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
logging:
  level:
    com.halo: debug
